### PR TITLE
Updating zenodo file

### PR DESCRIPTION
**Pull request by freemansw1**
Updates the zenodo file to fix the bugs.  I used this website: https://www.jsonschemavalidator.net/ to validate the JSON file and then used this schema description: https://zenodraft.github.io/metadata-schema-zenodo/latest/schema.json .

### CODE REVIEW

**Review by ldgrantcsu — COMMENTED** [review]
The zenodo file looks good to me. My only question @freemansw1 is why multiple previous commits you made are also showing up in the pull request. Is this from updating your fork?

**Comment by freemansw1** [comment]
Yes, that's from merging my fork (and from us doing a squash merge earlier). We can squash merge to get rid of them or just deal with the commit history

**Comment by freemansw1** [comment]
I should also note that updating my fork was a huge headache with the change in the folder inside of `src`. I would prefer that we get rid of that.

**Comment by ldgrantcsu** [comment]
Agreed.. yes that causes some unnecessary extra steps. OK looks good to me.

**Review by ldgrantcsu — APPROVED** [review]
Changes look good.

**Pull request merged**
